### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by CyberXcyborg**

### CODE REVIEW

**Comment by CyberXcyborg** [comment]
## Nyra Vale — Executive Code Review

### PR #21: Phase 24 — Enhanced Features & Ecosystem Maturity (v2.0.0-rc.1)

**Status: REQUEST CHANGES — Critical compilation issues found**

---

### 🔴 CRITICAL: Compilation Errors

**1. DataExport.cpp — Uses v1.x SPIFFS API (will not compile on v2.0)**
- Line:  — v2.0 migrated to LittleFS
- Uses , , ,  throughout
- Also references v1.x headers: , , , , 
- Calls  and  which are v1.x API
- **Fix**: Migrate to LittleFS or gate behind a v1.x compatibility flag

**2. PluginV2.cpp — Uses SPIFFS directly**
- Line:  and  
- **Fix**: Use LittleFS or the Storage_v2 abstraction

**3. VoicePrompts.cpp — Uses SPIFFS directly**
-  and all file operations use SPIFFS
- **Fix**: Migrate to LittleFS

---

### 🟡 LOGIC BUGS

**4. PowerManager_v2.cpp — Integer division truncates battery estimate**

When  and , this returns 6 instead of 6.0 — but worse, when , it returns 0, making the estimate useless at low battery.
- **Fix**: Cast to float: 

**5. PowerManager_v2.cpp — restoreStateFromRTC() silently does nothing**
The function validates RTC data but never actually writes it back to the pet. Comment acknowledges this: "Direct write not possible since getData() returns const ref."
- **Fix**: Either add a / method to PetEngine, or use  to restore

**6. DisplayDriver.cpp — Repeated ledcSetup/ledcAttachPin on every brightness change**
 calls  and  every invocation.
- **Fix**: Move to , call once

---

### 🟠 CODE QUALITY

**7. MemoryGameScreen.cpp — Fragile heap allocation in timer callback**

If LVGL timer is deleted before callback fires, memory leaks. Consider using stack-allocated data with shared_ptr or ensuring timer lifecycle.

**8. NFCManager.cpp — memcpy with fixed struct size on variable-length input**
 does  then checks length — potential buffer read beyond actual data if .
- **Fix**: Check  BEFORE the memcpy (the check exists but after memcpy)

---

### ✅ POSITIVE OBSERVATIONS

- 216/216 native tests pass — comprehensive coverage
- Good module separation and initialization patterns
- RTC memory checksum validation is solid
- BLE trade game state machine is well-designed
- Day/night transition interpolation is clean
- Game screens have proper lifecycle management
- Plugin watchdog concept is sound

---

### 📋 REQUIRED ACTIONS BEFORE RE-REVIEW

1. Fix SPIFFS → LittleFS in DataExport.cpp, PluginV2.cpp, VoicePrompts.cpp
2. Fix integer division in getEstimatedBatteryHoursV2()
3. Implement actual state restoration in restoreStateFromRTC()
4. Move ledcSetup/ledcAttachPin to DisplayDriver::begin()
5. Fix memcpy ordering in NFCManager::deserializeTradePayload()

Once these are addressed, I will approve. The architecture and test coverage are solid — just needs these compilation fixes.

**Comment by CyberXcyborg** [comment]
test
